### ISSUE TITLE
build pipeline shows failing on repo home page

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgeryimage#84]
The repo pipeline status is failing on home page. Shown in the following image from url https://github.com/UCL/scikit-surgeryimage 

<img width="1255" alt="Screenshot 2020-11-02 at 12 38 33" src="https://user-images.githubusercontent.com/2621305/97868895-6a949b80-1d08-11eb-8c7a-e06e16a29f9a.png">

**Comment by tdowrick** [comment]
Closing as pipeline is now fixed.
